### ISSUE TITLE
Reply to Brett?

### ISSUE THREAD

**Issue by jplock** [nickbabcock/dropwizard-hikaricp-benchmark#1]
Curious if you saw @brettwooldridge's comment on https://nbsoftsolutions.com/blog/the-difficulty-of-performance-evaluation-of-hikaricp-in-dropwizard how that impacts the testing

**Comment by nickbabcock** [comment]
Yeah we had a nice conversation on the [hikaricp forum](https://groups.google.com/forum/#!topic/hikari-cp/mOtyGp2fIeY) (definitely worth the read) where we essentially determined that when comparing apples to apples with respect to safety guarantees, performance of the connection pool didn't greatly factor into the latency of an HTTP request to the endpoint demonstrated in this project (1 HTTP request = 1 db request). The findings may change if there were `> 1` db interactions per HTTP request (or the db queries were longer).

**Comment by jplock** [comment]
Cool, thanks for the link
